Repository zb-developer2team/a-uction-BE, pull requests merged in 2023-04, with the labels that each got.

#10 001-project-setup
  a_uction/.gitignore
  a_uction/build.gradle
  a_uction/gradle/wrapper/gradle-wrapper.jar
  a_uction/gradle/wrapper/gradle-wrapper.properties
  a_uction/gradlew
  a_uction/gradlew.bat
  a_uction/settings.gradle
  a_uction/src/main/java/com/example/a_uction/AUctionApplication.java
  a_uction/src/main/resources/application.properties
  a_uction/src/test/java/com/example/a_uction/AUctionApplicationTests.java
Labels: init

#12 Feat/009/auction entity update
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/AuctionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/Category.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/ItemStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/TransactionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
Labels: feature

#19 [Feat/#13/register/0~1] 회원가입
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/model/user/controller/UserRegisterController.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/RegisterUser.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/repository/UserRepository.java
  a_uction/src/main/java/com/example/a_uction/model/user/service/UserRegisterService.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/resources/application.properties
  a_uction/src/main/resources/application.yml
  auction-user-api.http
Labels: feature

#26 feat: [Feat/#16/kakaoToken/2] RestTemplate Bean 등록
  a_uction/src/main/java/com/example/a_uction/config/RestTemplateConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/user/KakaoController.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/service/user/KakaoService.java
Labels: feature

#28 Feat/#27/create auction/0
  .idea/.gitignore
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/AuctionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/main/resources/application.yml
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/UserRegisterControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/UserRegisterServiceTest.java
Labels: feature

#30 Feat: feat/#23/auctionUpdate/0 updateAuction
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
Labels: feature

#33 feat/#32/readAuction/0
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
Labels: feature

#35 feat : [feat/#29/Jwt-0] Jwt 관련 로직 작성
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtProvider.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/UserRegisterControllerTest.java
Labels: feature

#34 [feat] feat/#23/auctionUpdate/1 AuctionController test 추가
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
Labels: feature

#36 [feat] feat/#23/readAuction/1
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
Labels: feature

#39 feat : [feat/#31/kakao login] 카카오 로그인 시 Jwt토큰 발급
  a_uction/src/main/java/com/example/a_uction/controller/user/KakaoController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/user/repository/UserRepository.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/service/user/KakaoService.java
Labels: feature

#43 [feat/#37/readAuction/2] #36 테스트 코드 / 토큰을 통해 사용자 정보 가져와 반영
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
Labels: feature

#44 feat: [Feat/#40/kakaoLogout] 카카오 로그아웃 구현 및 refreshToken 추가
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/RedisConfig.java
  a_uction/src/main/java/com/example/a_uction/config/RestTemplateConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/UserLoginController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/KakaoController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/LogoutUser.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtProvider.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/dto/TokenDto.java
  a_uction/src/main/java/com/example/a_uction/service/UserLoginService.java
  a_uction/src/main/java/com/example/a_uction/service/user/KakaoService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/UserLoginControllerTest.java
Labels: feature

#47 Feat/#46/modify user detail/0 회원정보 수정
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/UserInfoModifyController.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/ModifyUser.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/UserModifyService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/UserInfoModifyControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/UserModifyServiceTest.java
  auction-user-api.http
Labels: feature

#49 feat: [Feat/#48/reissueToken] 엑세스 토큰 갱신 구현
  a_uction/src/main/java/com/example/a_uction/controller/AuthController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/KakaoController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/exception/dto/ErrorResponse.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtProvider.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/dto/TokenDto.java
  a_uction/src/main/java/com/example/a_uction/service/user/AuthService.java
  a_uction/src/main/resources/application-jwt.yml
  auction-user-api.http
Labels: feature

#52 [Feat] Feat/#50/user info/0 회원정보 보기
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/controller/UserInfoController.java
  a_uction/src/main/java/com/example/a_uction/controller/UserInfoModifyController.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/InfoUser.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/ModifyUser.java
  a_uction/src/main/java/com/example/a_uction/service/UserInfoService.java
  a_uction/src/test/java/com/example/a_uction/controller/UserInfoControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/UserInfoServiceTest.java
  auction-user-api.http
Labels: feature

#53 Feat/#51/delete auction
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
Labels: feature

#55 [refactor] : refactor/#54/auctionStatus/0 AuctionStatus 삭제
  a_uction/src/main/java/com/example/a_uction/controller/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/AuctionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/Category.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/service/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
  auction-api.http
Labels: refactor

#57 [feat/#45/verify] 회원가입 핸드폰번호 인증 구현 + 이메일중복체크 기능 구현 + 모든 서비스코드 작성
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/SmsVerifyConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/UserRegisterController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/Verify.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserVerificationEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/repository/UserRepository.java
  a_uction/src/main/java/com/example/a_uction/model/user/repository/UserVerificationEntityRepository.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtProvider.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/dto/TokenDto.java
  a_uction/src/main/java/com/example/a_uction/service/UserLoginService.java
  a_uction/src/main/java/com/example/a_uction/service/UserRegisterService.java
  a_uction/src/main/java/com/example/a_uction/service/user/VerifyService.java
  a_uction/src/test/java/com/example/a_uction/controller/UserRegisterControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/UserLoginServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/UserRegisterServiceTest.java
  auction-verify-api.http
Labels: feature

#61 update : [update/#60/testCode] 테스트코드 관련 전부 수정 + 테스트케이스 추가
  a_uction/src/main/java/com/example/a_uction/controller/UserRegisterController.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtProvider.java
  a_uction/src/test/java/com/example/a_uction/controller/UserRegisterControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/VerifyServiceTest.java
  auction-verify-api.http
Labels: refactor

#65 feat: [Feat/#58/tokenError] 필터에서 토큰 인증 실패시 적절한 예외 처리
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtProvider.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/dto/TokenDto.java
  a_uction/src/test/java/com/example/a_uction/service/UserLoginServiceTest.java
Labels: feature

#69 refector: [feat/#68/refector] 리팩토링
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/AuthController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/UserInfoController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/UserLoginController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/UserRegisterController.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/user/KakaoService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserInfoService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserLoginService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserRegisterService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/user/UserInfoControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/user/UserLoginControllerTest.java
  a_uction/src/test/java/com/example/a_uction/controller/user/UserRegisterControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/UserInfoServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/UserLoginServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/UserRegisterServiceTest.java
  auction-api.http
  auction-user-api.http
Labels: refactor

#71 refactor/#70/joinTables/0
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/repository/UserRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: refactor

#72 feat : [feat/#67/ElasticSearch/0] elasticsearch 구현
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/ElasticSearchConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionSearchController.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDocumentResponse.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/SearchCondition.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionDocument.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionSearchQueryRepository.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionSearchRepository.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionSearchService.java
  a_uction/src/main/resources/elastic/auction-mapping.json
  a_uction/src/main/resources/elastic/auction-setting.json
  auction-api.http
  elastic-search.http
Labels: feature

#78 [Feat/#59/chat 0] WebSocket 설정과 메세지가 오가는 flow 구현
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/ChatInterceptor.java
  a_uction/src/main/java/com/example/a_uction/config/WebSocketConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/chat/ChatController.java
  a_uction/src/main/java/com/example/a_uction/model/chat/constants/MessageType.java
  a_uction/src/main/java/com/example/a_uction/model/chat/dto/ChatMessage.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
Labels: feature

#80 Refactor/#79/user&auction refactor/0
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/InfoUser.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/ModifyUser.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserInfoService.java
  a_uction/src/test/java/com/example/a_uction/controller/user/UserInfoControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/UserInfoServiceTest.java
  auction-user-api.http
Labels: refactor

#81 Feat/#73/elastic search/0
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionSearchController.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionSearchService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
Labels: feature

#82 feat : [feat/#59/chat-1] websocket configuration & chat 구현
  a_uction/src/main/java/com/example/a_uction/config/RedisConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/chat/ChatController.java
  a_uction/src/main/java/com/example/a_uction/model/chat/dto/Message.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatApplication.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: feature

#85 refactor : [refactor/#83/verification-0]
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/Verify.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserVerificationEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/repository/UserVerificationEntityRepository.java
  a_uction/src/main/java/com/example/a_uction/service/user/AuthService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserRegisterService.java
  a_uction/src/main/java/com/example/a_uction/service/user/VerifyService.java
  a_uction/src/test/java/com/example/a_uction/service/user/VerifyServiceTest.java
Labels: refactor

#87 refactor : [refactor/#86/endpoint-0]
  a_uction/src/main/java/com/example/a_uction/controller/TimeController.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/chat/ChatController.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserRegisterService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/UserRegisterServiceTest.java
  auction-api.http
Labels: refactor

#89 Feat : [feat/#88/auctionList/0] 상태별 auction list 보기
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/AuctionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/Category.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/ItemStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/TransactionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
  auction-api.http
Labels: feature

#91 Feat/#74/create bid 경매 입찰 생성
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/RedisRepositoryConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/chat/ChatController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/dto/BiddingHistoryDto.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/entity/BiddingHistoryEntity.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/repository/BiddingHistoryRepository.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
Labels: feature

#92 refactor : [refactor/#84/chat-refactor-0]
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/WebSocketConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/TreadEndpoint.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatApplication.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
  a_uction/src/main/resources/application.yml
  auction-api.http
Labels: refactor

#95 feat: [feat/#93/s3] 경매 파일 업로드 및 s3업로드 기능 구현
  a_uction/build.gradle
  a_uction/src/main/java/com/example/a_uction/config/AwsS3Config.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/s3/S3Controller.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/file/dto/File.java
  a_uction/src/main/java/com/example/a_uction/model/file/entity/FileEntity.java
  a_uction/src/main/java/com/example/a_uction/model/file/repository/FileRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/auction/FileService.java
  a_uction/src/main/java/com/example/a_uction/service/s3/S3Service.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserBalanceService.java
  a_uction/src/main/resources/application-rabbitmq.yml
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/FileServiceTest.java
  a_uction/src/test/resources/image/test.png
  auction-api.http
Labels: feature

#99 Refactor : [Refactor/#98/elasticSearchSort/0] elastic search refactor
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionSearchController.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDocumentResponse.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionSearchQueryRepository.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionSearchRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionSearchService.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  elastic-search.http
Labels: refactor

#100 Feat/#96/auction enhancement
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/biddingHistory/BiddingHistoryController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/constants/TransactionStatus.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/dto/AuctionTransactionHistoryDto.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/entity/AuctionTransactionHistoryEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/repository/AuctionTransactionHistoryRepository.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/dto/BiddingHistoryDto.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/entity/BiddingHistoryEntity.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/repository/BiddingHistoryRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/biddingHistory/BiddingHistoryService.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: enhancement

#101 refactor : [refactor/#97/refactor_fileEntity-0] 경매 이미지 관련 코드 리팩터링
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/s3/S3Controller.java
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auction/repository/AuctionRepository.java
  a_uction/src/main/java/com/example/a_uction/model/file/dto/File.java
  a_uction/src/main/java/com/example/a_uction/model/file/entity/FileEntity.java
  a_uction/src/main/java/com/example/a_uction/model/file/repository/FileRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionFileService.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/auction/FileService.java
  a_uction/src/main/java/com/example/a_uction/service/s3/S3Service.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionFileServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/FileServiceTest.java
  auction-api.http
Labels: refactor

#103 feature : [feat/#102/user-profile-image-0] 유저프로필이미지 등록, 수정, 삭제 기능구현
  a_uction/src/main/java/com/example/a_uction/controller/user/UserInfoController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/InfoUser.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/ModifyUser.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/service/user/KakaoService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserInfoService.java
  a_uction/src/test/java/com/example/a_uction/controller/user/UserInfoControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/user/UserInfoServiceTest.java
  auction-user-api.http
Labels: feature

#106 feat & refactor : [feat/#105/auction-transaction-history-image]
  a_uction/src/main/java/com/example/a_uction/model/auction/dto/AuctionDto.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/dto/AuctionTransactionHistoryDto.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/entity/AuctionTransactionHistoryEntity.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionFileService.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionFileServiceTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: feature

#107 refactor/#104/biddingHistoryRefactor/0
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/entity/AuctionTransactionHistoryEntity.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/dto/BiddingHistoryDto.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/entity/BiddingHistoryEntity.java
  a_uction/src/main/java/com/example/a_uction/model/biddingHistory/repository/BiddingHistoryRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/biddingHistory/BiddingHistoryService.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
  auction-user-api.http
Labels: refactor

#109 [refactor: refactor/#108/deploy] 배포를 위한 ElasticSearchConfig 코드 변경
  a_uction/src/main/java/com/example/a_uction/config/ElasticSearchConfig.java
  a_uction/src/main/java/com/example/a_uction/config/RedisRepositoryConfig.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
Labels: refactor

#111 Refactor : [Refactor/#110/elasticSearch/0] elastic search - item name sort 기준 변경
  a_uction/src/main/java/com/example/a_uction/config/ElasticSearchConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/search/AuctionSearchController.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/dto/AuctionDocumentResponse.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/dto/ItemNameSearchCondition.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/dto/SearchCondition.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/entity/AuctionDocument.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/repository/AuctionSearchQueryRepository.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/repository/AuctionSearchRepository.java
  a_uction/src/main/java/com/example/a_uction/service/search/AuctionSearchService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  elastic-search.http
Labels: refactor

#113 Refactor : [Refactor/#112/searchSortRefactor/0] elastic search sort refactor
  a_uction/src/main/java/com/example/a_uction/controller/search/AuctionSearchController.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/constants/SortProperties.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/dto/AuctionDocumentResponse.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/dto/SortingCondition.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/entity/AuctionDocument.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/repository/AuctionSearchQueryRepository.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/repository/AuctionSearchRepository.java
  a_uction/src/main/java/com/example/a_uction/service/search/AuctionSearchService.java
  a_uction/src/main/resources/elastic/auction-mapping.json
  elastic-search.http
Labels: refactor

#115 feat/#114/auctionTransactionHistory/0
  a_uction/src/main/java/com/example/a_uction/controller/auctionTransactionHistory/AuctionTransactionHistoryController.java
  a_uction/src/main/java/com/example/a_uction/controller/biddingHistory/BiddingHistoryController.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/dto/AuctionTransactionHistoryDto.java
  a_uction/src/main/java/com/example/a_uction/model/auctionTransactionHistory/repository/AuctionTransactionHistoryRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auctionTransactionHistory/AuctionTransactionHistoryService.java
  a_uction/src/main/java/com/example/a_uction/service/biddingHistory/BiddingHistoryService.java
  auction-api.http
  auction-user-api.http
Labels: feature

#118 Feat/#116/wish list/0 관심등록 구현
  a_uction/src/main/java/com/example/a_uction/controller/wish/WishController.java
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/model/auction/entity/AuctionEntity.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/model/wishList/dto/WishListResponse.java
  a_uction/src/main/java/com/example/a_uction/model/wishList/entity/WishListEntity.java
  a_uction/src/main/java/com/example/a_uction/model/wishList/repository/WishRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/wish/WishService.java
  a_uction/src/test/java/com/example/a_uction/controller/wish/WishControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/wish/WishServiceTest.java
  auction-wish-api.http
Labels: feature

#120 [feat/#119/auction-end-0] 경매 종료 구현
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/test/java/com/example/a_uction/controller/auction/AuctionControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: feature

#122 Refactor/#121/search refactor/0
  a_uction/src/main/java/com/example/a_uction/controller/search/AuctionSearchController.java
  a_uction/src/main/java/com/example/a_uction/model/auctionSearch/repository/AuctionSearchQueryRepository.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/search/AuctionSearchService.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
  elastic-search.http
Labels: refactor
