Repository zb-developer2team/a-uction-BE, pull requests merged in 2023-05, with the labels that each got.

#127 feat/#126/getCurrentPrice/
  a_uction/src/main/java/com/example/a_uction/controller/biddingHistory/BiddingHistoryController.java
  a_uction/src/main/java/com/example/a_uction/service/biddingHistory/BiddingHistoryService.java
Labels: feature

#123 [feat/#117/webconfig] webconfig 과 health-check
  a_uction/src/main/java/com/example/a_uction/config/WebConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/HealthCheckController.java
  a_uction/src/main/java/com/example/a_uction/model/user/entity/UserEntity.java
  a_uction/src/main/java/com/example/a_uction/security/config/SecurityConfig.java
  a_uction/src/main/java/com/example/a_uction/security/jwt/JwtAuthenticationFilter.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
Labels: refactor, feature

#125 Feat : [feat/#124/wish-list/0] 경매 종료시 wish list 삭제
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: feature

#130 [feat/#129/deploy-version-upgrade] form 생성(email, phoneNumber), webso…
  a_uction/src/main/java/com/example/a_uction/config/MultipartJackson2HttpMessageConverter.java
  a_uction/src/main/java/com/example/a_uction/config/WebSocketConfig.java
  a_uction/src/main/java/com/example/a_uction/controller/auction/AuctionController.java
  a_uction/src/main/java/com/example/a_uction/controller/user/UserRegisterController.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/EmailForm.java
  a_uction/src/main/java/com/example/a_uction/model/user/dto/PhoneNumberForm.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserRegisterService.java
  a_uction/src/test/java/com/example/a_uction/controller/user/UserRegisterControllerTest.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: feature

#131 refactor: [refactor/#128/bidding-finished] 경매 종료시 최종 입찰자 예치금 인출 추가
  a_uction/src/main/java/com/example/a_uction/exception/constants/ErrorCode.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: refactor

#134 [feat/#132/chat-refactor] form 입력하던 구조에서 contensts 만 입력할 수 있도록 변경
  a_uction/src/main/java/com/example/a_uction/config/ChatInterceptor.java
  a_uction/src/main/java/com/example/a_uction/controller/chat/ChatController.java
  a_uction/src/main/java/com/example/a_uction/service/auction/AuctionService.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatApplication.java
  a_uction/src/main/java/com/example/a_uction/service/chat/ChatMessageService.java
  a_uction/src/main/java/com/example/a_uction/service/user/UserBalanceService.java
  a_uction/src/test/java/com/example/a_uction/service/auction/AuctionServiceTest.java
Labels: refactor, feature
